import {
  DNA,
  Bone,
  Bones,
  Beacon,
  Blister,
  Crutches,
  Ambulance,
  BrokenBone,
  Documentation,
  BloodTypePlus,
  BloodTypeMinus,
  CalendarWaiting,
  CalendarApproved,
  CalendarDeclined,
  Drip,
  EmergencyPhone,
  EyeDisabled,
  Eye,
  FirstAidKit,
  Heartbeat,
  Hospital1,
  HospitalBed,
  Mask,
  MedicalDocumentation,
  MedicalNote,
  Microscope,
  Monitoring,
  NarrowDrugPackage,
  Nose,
  Nurse,
  Patches,
  Pharmacy,
  Pill,
  Pills,
  Pipette,
  SmartwatchHeart,
  SmartwatchPulse,
  Smartwatch,
  Stethoscope,
  Syringe,
  Thermometer,
  Vial,
  Virus,
  Weight,
  Doctor,
  Tooth,
  Calendar,
  WideDrugPackage,
  BloodGlucose,
  BloodPressure,
  Bone2,
  Brain,
  Buttocks,
  Cell,
  DNA2,
  Detection,
  Ear,
  Eye2,
  Foot2,
  Hand,
  Health,
  Heart,
  HeartRate,
  Injection,
  Intestine,
  Kidney,
  Knee,
  Liver,
  Lungs,
  Medicine,
  Mouth,
  Neural,
  Nose2,
  Pill2,
  Stomach,
  Temperature,
  Thigh,
  Tooth2,
  Uterus,
  Virus2,
  Waist,
  ankle,
  assay,
  Medicare1,
  Medicare10,
  Medicare100,
  Medicare101,
  Medicare102,
  Medicare103,
  Medicare104,
  Medicare105,
  Medicare106,
  Medicare107,
  Medicare108,
  Medicare109,
  Medicare11,
  Medicare110,
  Medicare12,
  Medicare13,
  Medicare14,
  Medicare15,
  Medicare16,
  Medicare17,
  Medicare18,
  Medicare19,
  Medicare2,
  Medicare20,
  Medicare21,
  Medicare22,
  Medicare23,
  Medicare24,
  Medicare25,
  Medicare26,
  Medicare27,
  Medicare28,
  Medicare29,
  Medicare3,
  Medicare30,
  Medicare31,
  Medicare32,
  Medicare33,
  Medicare34,
  Medicare35,
  Medicare36,
  Medicare37,
  Medicare38,
  Medicare39,
  Medicare4,
  Medicare40,
  Medicare41,
  Medicare42,
  Medicare43,
  Medicare44,
  Medicare45,
  Medicare46,
  Medicare47,
  Medicare48,
  Medicare49,
  Medicare5,
  Medicare50,
  Medicare51,
  Medicare52,
  Medicare53,
  Medicare54,
  Medicare55,
  Medicare56,
  Medicare57,
  Medicare58,
  Medicare59,
  Medicare6,
  Medicare60,
  Medicare61,
  Medicare62,
  Medicare63,
  Medicare64,
  Medicare65,
  Medicare66,
  Medicare67,
  Medicare68,
  Medicare69,
  Medicare7,
  Medicare70,
  Medicare71,
  Medicare72,
  Medicare73,
  Medicare74,
  Medicare75,
  Medicare76,
  Medicare77,
  Medicare78,
  Medicare79,
  Medicare8,
  Medicare80,
  Medicare81,
  Medicare82,
  Medicare83,
  Medicare84,
  Medicare85,
  Medicare86,
  Medicare87,
  Medicare88,
  Medicare89,
  Medicare9,
  Medicare90,
  Medicare91,
  Medicare92,
  Medicare93,
  Medicare94,
  Medicare95,
  Medicare96,
  Medicare97,
  Medicare98,
  Medicare99,
} from '@/shared/assets/Pages/Departments';

export const iconsCardDepartments = [
  { icon: Ambulance },
  { icon: Beacon },
  { icon: Blister },
  { icon: BloodTypeMinus },
  { icon: BloodTypePlus },
  { icon: Bone },
  { icon: Bones },
  { icon: BrokenBone },
  { icon: CalendarApproved },
  { icon: CalendarDeclined },
  { icon: CalendarWaiting },
  { icon: Calendar },
  { icon: Crutches },
  { icon: DNA },
  { icon: Doctor },
  { icon: Documentation },
  { icon: Drip },
  { icon: EmergencyPhone },
  { icon: EyeDisabled },
  { icon: Eye },
  { icon: FirstAidKit },
  { icon: Heartbeat },
  { icon: Hospital1 },
  { icon: HospitalBed },
  { icon: Mask },
  { icon: MedicalDocumentation },
  { icon: MedicalNote },
  { icon: Microscope },
  { icon: Monitoring },
  { icon: NarrowDrugPackage },
  { icon: Nose },
  { icon: Nurse },
  { icon: Patches },
  { icon: Pharmacy },
  { icon: Pill },
  { icon: Pills },
  { icon: Pipette },
  { icon: SmartwatchHeart },
  { icon: SmartwatchPulse },
  { icon: Smartwatch },
  { icon: Stethoscope },
  { icon: Syringe },
  { icon: Thermometer },
  { icon: Tooth },
  { icon: Vial },
  { icon: Virus },
  { icon: Weight },
  { icon: WideDrugPackage },
  { icon: DNA2 },
  { icon: ankle },
  { icon: assay },
  { icon: BloodGlucose },
  { icon: BloodPressure },
  { icon: Bone2 },
  { icon: Brain },
  { icon: Buttocks },
  { icon: Cell },
  { icon: Detection },
  { icon: Ear },
  { icon: Eye2 },
  { icon: Foot2 },
  { icon: Hand },
  { icon: Health },
  { icon: HeartRate },
  { icon: Heart },
  { icon: Injection },
  { icon: Intestine },
  { icon: Kidney },
  { icon: Knee },
  { icon: Liver },
  { icon: Medicine },
  { icon: Lungs },
  { icon: Mouth },
  { icon: Neural },
  { icon: Nose2 },
  { icon: Pill2 },
  { icon: Stomach },
  { icon: Temperature },
  { icon: Thigh },
  { icon: Tooth2 },
  { icon: Uterus },
  { icon: Virus2 },
  { icon: Waist },
  { icon: Medicare1 },
  { icon: Medicare2 },
  { icon: Medicare3 },
  { icon: Medicare4 },
  { icon: Medicare5 },
  { icon: Medicare6 },
  { icon: Medicare7 },
  { icon: Medicare8 },
  { icon: Medicare9 },
  { icon: Medicare10 },
  { icon: Medicare11 },
  { icon: Medicare12 },
  { icon: Medicare13 },
  { icon: Medicare14 },
  { icon: Medicare15 },
  { icon: Medicare16 },
  { icon: Medicare17 },
  { icon: Medicare18 },
  { icon: Medicare19 },
  { icon: Medicare20 },
  { icon: Medicare21 },
  { icon: Medicare22 },
  { icon: Medicare23 },
  { icon: Medicare24 },
  { icon: Medicare25 },
  { icon: Medicare26 },
  { icon: Medicare27 },
  { icon: Medicare28 },
  { icon: Medicare29 },
  { icon: Medicare30 },
  { icon: Medicare31 },
  { icon: Medicare32 },
  { icon: Medicare33 },
  { icon: Medicare34 },
  { icon: Medicare35 },
  { icon: Medicare36 },
  { icon: Medicare37 },
  { icon: Medicare38 },
  { icon: Medicare39 },
  { icon: Medicare40 },
  { icon: Medicare41 },
  { icon: Medicare42 },
  { icon: Medicare43 },
  { icon: Medicare44 },
  { icon: Medicare45 },
  { icon: Medicare46 },
  { icon: Medicare47 },
  { icon: Medicare48 },
  { icon: Medicare49 },
  { icon: Medicare50 },
  { icon: Medicare51 },
  { icon: Medicare52 },
  { icon: Medicare53 },
  { icon: Medicare54 },
  { icon: Medicare55 },
  { icon: Medicare56 },
  { icon: Medicare57 },
  { icon: Medicare58 },
  { icon: Medicare59 },
  { icon: Medicare60 },
  { icon: Medicare61 },
  { icon: Medicare62 },
  { icon: Medicare63 },
  { icon: Medicare64 },
  { icon: Medicare65 },
  { icon: Medicare66 },
  { icon: Medicare67 },
  { icon: Medicare68 },
  { icon: Medicare69 },
  { icon: Medicare70 },
  { icon: Medicare71 },
  { icon: Medicare72 },
  { icon: Medicare73 },
  { icon: Medicare74 },
  { icon: Medicare75 },
  { icon: Medicare76 },
  { icon: Medicare77 },
  { icon: Medicare78 },
  { icon: Medicare79 },
  { icon: Medicare80 },
  { icon: Medicare81 },
  { icon: Medicare82 },
  { icon: Medicare83 },
  { icon: Medicare84 },
  { icon: Medicare85 },
  { icon: Medicare86 },
  { icon: Medicare87 },
  { icon: Medicare88 },
  { icon: Medicare89 },
  { icon: Medicare90 },
  { icon: Medicare91 },
  { icon: Medicare92 },
  { icon: Medicare93 },
  { icon: Medicare94 },
  { icon: Medicare95 },
  { icon: Medicare96 },
  { icon: Medicare97 },
  { icon: Medicare98 },
  { icon: Medicare99 },
  { icon: Medicare100 },
  { icon: Medicare101 },
  { icon: Medicare102 },
  { icon: Medicare103 },
  { icon: Medicare104 },
  { icon: Medicare105 },
  { icon: Medicare106 },
  { icon: Medicare107 },
  { icon: Medicare108 },
  { icon: Medicare109 },
  { icon: Medicare110 },
];
